// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUIPossibilitiesPageObjects.UIMap1Classes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public partial class UIMap1
    {
        
        #region Properties
        public UIStarwarsSzukajwGooglWindow UIStarwarsSzukajwGooglWindow
        {
            get
            {
                if ((this.mUIStarwarsSzukajwGooglWindow == null))
                {
                    this.mUIStarwarsSzukajwGooglWindow = new UIStarwarsSzukajwGooglWindow();
                }
                return this.mUIStarwarsSzukajwGooglWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIStarwarsSzukajwGooglWindow mUIStarwarsSzukajwGooglWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIStarwarsSzukajwGooglWindow : BrowserWindow
    {
        
        public UIStarwarsSzukajwGooglWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "star wars - Szukaj w Google - Internet Explorer";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("star wars - Szukaj w Google - Internet Explorer");
            this.WindowTitles.Add("Wikipedia, wolna encyklopedia - Internet Explorer");
            this.WindowTitles.Add("Wikipedia, la enciclopedia libre - Internet Explorer");
            this.WindowTitles.Add("Testowanie eksploracyjne – Wikipedia, wolna encyklopedia - Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UITestowanieeksploracyDocument UITestowanieeksploracyDocument
        {
            get
            {
                if ((this.mUITestowanieeksploracyDocument == null))
                {
                    this.mUITestowanieeksploracyDocument = new UITestowanieeksploracyDocument(this);
                }
                return this.mUITestowanieeksploracyDocument;
            }
        }
        #endregion
        
        #region Fields
        private UITestowanieeksploracyDocument mUITestowanieeksploracyDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITestowanieeksploracyDocument : HtmlDocument
    {
        
        public UITestowanieeksploracyDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Testowanie eksploracyjne – Wikipedia, wolna encyklopedia";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/wiki/Testowanie_eksploracyjne";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pl.wikipedia.org/wiki/Testowanie_eksploracyjne";
            this.WindowTitles.Add("Testowanie eksploracyjne – Wikipedia, wolna encyklopedia - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIMwheadPane
        {
            get
            {
                if ((this.mUIMwheadPane == null))
                {
                    this.mUIMwheadPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIMwheadPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "mw-head";
                    this.mUIMwheadPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMwheadPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Narzędzia osobiste \n\nNie jesteś zalogo";
                    this.mUIMwheadPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMwheadPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIMwheadPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"mw-head\"";
                    this.mUIMwheadPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "24";
                    this.mUIMwheadPane.WindowTitles.Add("Testowanie eksploracyjne – Wikipedia, wolna encyklopedia - Internet Explorer");
                    #endregion
                }
                return this.mUIMwheadPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIMwheadPane;
        #endregion
    }
}
