// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUIPossibilitiesProject.UIMap1Classes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public partial class UIMap1
    {
        
        #region Properties
        public UIGoogleInternetExplorWindow UIGoogleInternetExplorWindow
        {
            get
            {
                if ((this.mUIGoogleInternetExplorWindow == null))
                {
                    this.mUIGoogleInternetExplorWindow = new UIGoogleInternetExplorWindow();
                }
                return this.mUIGoogleInternetExplorWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleInternetExplorWindow mUIGoogleInternetExplorWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIGoogleInternetExplorWindow : BrowserWindow
    {
        
        public UIGoogleInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Google - Internet Explorer";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Google - Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGoogleDocument UIGoogleDocument
        {
            get
            {
                if ((this.mUIGoogleDocument == null))
                {
                    this.mUIGoogleDocument = new UIGoogleDocument(this);
                }
                return this.mUIGoogleDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleDocument mUIGoogleDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIGoogleDocument : HtmlDocument
    {
        
        public UIGoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.google.pl/#spf=1627581343006";
            this.WindowTitles.Add("Google - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISzukajEdit
        {
            get
            {
                if ((this.mUISzukajEdit == null))
                {
                    this.mUISzukajEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISzukajEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUISzukajEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUISzukajEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISzukajEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISzukajEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Szukaj";
                    this.mUISzukajEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "gLFyf gsfi";
                    this.mUISzukajEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" title=\"Szukaj\" class=\"gLFyf gsf";
                    this.mUISzukajEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUISzukajEdit.WindowTitles.Add("Google - Internet Explorer");
                    #endregion
                }
                return this.mUISzukajEdit;
            }
        }
        
        public HtmlInputButton UISzukajwGoogleButton
        {
            get
            {
                if ((this.mUISzukajwGoogleButton == null))
                {
                    this.mUISzukajwGoogleButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISzukajwGoogleButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISzukajwGoogleButton.SearchProperties[HtmlButton.PropertyNames.Name] = "btnK";
                    this.mUISzukajwGoogleButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Szukaj w Google";
                    this.mUISzukajwGoogleButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISzukajwGoogleButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISzukajwGoogleButton.FilterProperties[HtmlButton.PropertyNames.Class] = "gNO89b";
                    this.mUISzukajwGoogleButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"btnK\" class=\"gNO89b\" aria-label=\"S";
                    this.mUISzukajwGoogleButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "9";
                    this.mUISzukajwGoogleButton.WindowTitles.Add("Google - Internet Explorer");
                    #endregion
                }
                return this.mUISzukajwGoogleButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISzukajEdit;
        
        private HtmlInputButton mUISzukajwGoogleButton;
        #endregion
    }
}
